routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware('auth');

// Admin Routes
Route::namespace('Admin')->middleware('auth')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace

    // Program Routes
    Route::resource('programs', 'ProgramController');
    Route::resource('modules', 'ModuleController');

    // Nested Route for Programs & Modules
    Route::resource('programs.modules', 'ModuleProgramController');

    // Batch
    Route::resource('batches', 'BatchController');
    Route::resource('batches.students', 'BatchStudentController');

    Route::resource('students', 'StudentController');
    Route::resource('vendors', 'VendorController');
    Route::resource('customers', 'CustomerController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('incomes', 'IncomeController');

    Route::get('export', 'StudentController@export')->name('export');
    Route::post('import', 'StudentController@import')->name('import');




});

app/Program.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{

    // Set Default Value
    protected $attributes = [ 'total_credit' => 0];

    // Mass Assignable Fields
    protected $fillable = [
        'program_level_id',
        'name',
        'short_code',
        'status',
        'total_credit'
    ];

    /* Relationships */
    public function level()
    {
        return $this->hasOne('App\ProgramLevel', 'id', 'program_level_id');
    }

    public function modules()
    {
        return $this->belongsToMany('App\Module');
    }
}

app/Http/Controllers/Admin/ProgramController.php
<?php

namespace App\Http\Controllers\Admin;

use App\ProgramLevel;
use App\Program;
use App\Module;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProgramRequest;

class ProgramController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // Get list of Programs
        $programs = Program::when($request->input('q'), function ($query, $q) {
            return $query->where('short_code', 'LIKE', "%${q}%")->orWhere('name', 'LIKE', "%${q}%");
            })->orderBy('name', 'asc')->paginate(14);
        
        // Get Levels
        $levels = ProgramLevel::all()->sortBy('sort_order')->groupBy('type');
        
        // Return to view
        return view('admin.programs.index', compact('programs', 'levels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProgramRequest $request)
    {   
        // Create Program
        Program::create($request->all());

        // Redirect to index page
        return redirect()->back()->with('success', 'Program Created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Program $program)
    {
        $program->load(['level', 'modules']);

        // Send All Modules
        $add_modules = Module::whereDoesntHave('programs', function($q) use($program)
        {
            $q->where('program_id', $program->id);
         })->get();

        return view('admin.programs.show', compact('program', 'add_modules'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Program $program)
    {   
        $levels = ProgramLevel::all()->sortBy('sort_order')->groupBy('type');
        return view('admin.programs.edit', compact('program', 'levels'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProgramRequest $request, Program $program)
    {
        // Get Program
        $program->update($request->all());
        
        // Redirect back to Index
        return redirect()->route('programs.index')->with('success', 'Program Updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Program $program)
    {
        $program->delete();
        return redirect()->route('programs.index')->with('danger', 'Program Deleted successfully!');
    }
}

resources/views/admin/programs/create.blade.php
<!-- Modal -->
<div class="modal fade slide-up" id="create-program" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content">
        <div class="modal-header clearfix text-left">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i></button>
          <h5><span class="semi-bold">Add Program</span></h5>
          <p class="p-b-10">Please make sure all the required information is filled</p>
        </div>
        
        <div class="modal-body">
          {{ Form::open(['route' => 'programs.store', 'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal']) }}
            @include('admin.programs.form') 
          {{ Form::close() }}
        </div>

      </div>
    </div>
    <!-- /.modal-content -->
  </div>
</div>

resources/views/admin/programs/edit.blade.php
@extends('layouts.admin')

@section('title', 'Program')
@section('content')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
      <div class="col-lg-4 pull-right">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('programs.index') }}">Programs</a></li>
          <li class="breadcrumb-item active">Edit Program</li>
        </ol>
      </div>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class="no-padding container-fixed-lg bg-white">
      <div class="d-flex justify-content-center ">
          <div class="container card card-default col-6 mt-3">
              <!-- START card -->
                <div class="card-header ">
                  <h5>Edit Program</h5>
                  <div class="pull-right">
                    <div class="col-xs-12">
                    </div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="card-block">
                  {{ Form::model($program, ['route' => ['programs.update', $program],'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal' ]) }}
                  {{ method_field('PATCH') }}
                      @include('admin.programs.form')
                  {{ Form::close() }}
                </div>
              <!-- END card -->
            </div>
      </div>


    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/programs/form.blade.php
<div class="row">
  <div class="col-md-8">
    <div class="form-group form-group-default required {{ $errors->has('short_code') ? 'has-error' :'' }}">
      {{ Form::label('Short Code') }}
      {{ Form::text('short_code', null, ['class' => 'form-control', 'placeholder' => 'Short Code', 'required',]) }}
    </div>
    {!! $errors->first('short_code', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<div class="row clearfix">
  <div class="col-md-12">
    <div class="form-group form-group-default required {{ $errors->has('name') ? 'has-error' :'' }}">
      {{ Form::label('Program name') }}
      {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Program Name', 'required']) }}
    </div>
    {!! $errors->first('name', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<div class="row clearfix">
  <div class="col-md-6">
    <div class="form-group form-group-default form-group-default-select2 required">
      <label class="">Program Level</label>
      <select class="full-width" data-placeholder="Select Level" data-init-plugin="select2" name="program_level_id">
        @foreach ($levels as $type => $levelGrouped)
          <optgroup label="{{ $type }}">
            @foreach ($levelGrouped as $level)
              <option value="{{ $level->id }}" {{ isset($program) ? ($program->program_level_id == $level->id ? 'selected' : '') : '' }}>{{ $level->name }}</option>
            @endforeach
          </optgroup>
        @endforeach
      </select>
    </div>
  </div>

  <div class="col-md-6">
      <div class="form-group form-group-default form-group-default-select2 required">
        {{ Form::label('Status') }}
        {{ Form::select('status', config('uyoon.programs.status'), null, ['class' => 'full-width', 'data-init-plugin' => 'select2', 'data-disable-search' => 'true']) }}
      </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-8">
  </div>
  <div class="col-md-4 m-t-10 sm-m-t-10">
    {{ Form::submit(isset($program) ? 'Update Program' : 'Add Program', ['class' => 'btn btn-primary btn-block m-t-5']) }}
  </div>
</div>

resources/views/admin/programs/index.blade.php
@extends('layouts.admin')

@section('title', 'Programs')

@section('content')

@include('admin.programs.create')
@include('shared.notifications')

<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="inner" style="transform: translateY(0px); opacity: 1;">
      <!-- START BREADCRUMB -->
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Programs</li>
      </ol>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" no-padding    container-fixed-lg bg-white">
      <div class="container card card-default">
        <!-- START card -->
        <div class="card card-transparent">
          <div class="card-header ">
            <a class="btn btn-primary btn-cons" href="#" data-target="#create-program" data-toggle="modal">Add Program</a>
            <div class="pull-right">
              <div class="col-xs-12">
                <form action="{{ route('programs.index') }}">
                    <div class="input-group transparent center-margin">
                        <input type="text" name="q" class="form-control pull-right" placeholder="Search" value="{{ request()->input('q') }}">
                        <span class="input-group-addon ">
                            <i class="pg-search"></i>
                        </span>
                    </div>
                </form>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="card-block">

            <div class="table-responsive">
              <div  class="dataTables_wrapper no-footer">
                <table class="table table-hover table-condensed dataTable no-footer" role="grid">
                  <thead>
                    <tr role="row">
                      <th style="width: 10%">Code</th>
                      <th style="width: 40%">Name</th>
                      <th style="width: 10%">Credit</th>
                      <th style="width: 20%">Status</th>
                      <th style="width: 30%">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($programs as $program)
                    <tr>
                        <td class="v-align-middle">{{ $program->short_code }}</td>
                      <td class="v-align-middle semi-bold"><a href="{{ route('programs.show', $program) }}">{{ $program->name }}</a></td>
                      <td class="v-align-middle semi-bold">{{ $program->total_credit }}</td>
                      <td class="v-align-middle semi-bold">{{ $program->status }}</td>
                      <td class="v-align-middle semi-bold">
                        <a href="{{ route('programs.edit', $program) }}">Edit</a>
                        <div class="vertical-line"></div>
                        <form action="{{ route('programs.destroy', ['id' => $program->id ]) }}?_method=DELETE" class="delete-onclick inline" method="POST">
                          @csrf
                          <button class="btn text-danger btn-link m-0 p-0" type="submit">Delete</button>
                          </button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>

            {{-- Default Empty State --}}
            @component('shared.empty', ['route' => 'programs.index', 'model' => 'programs', 'data' => $programs])
              {{-- Create new Bttn --}}
              <a class="btn btn-primary btn-cons" href="#" data-target="#create-program" data-toggle="modal">Add Program</a>
            @endcomponent

            <div class="mt-3">
                {{ $programs->links() }}
            </div>
          </div>
        </div>
        <!-- END card -->
      </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/programs/show.blade.php
@extends('layouts.admin')

@section('title', 'Programs')

@section('content')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
      <div class="col-lg-6 pull-right">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('programs.index') }}">Programs</a></li>
          <li class="breadcrumb-item active">{{ $program->name }}</li>
        </ol>
      </div>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" no-padding container-fixed-lg bg-white">
      <div class="container card card-default">
        <!-- START card -->
        <div class="card card-transparent">
          <div class="card-header ">
            <h3 class=" no-margin">{{ $program->name }}</h3>
            <div class="pull-right">
              <div class="col-xs-12">
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="card-block">
            <div class="row">
              <!-- START card -->
              <div class="card card-transparent">
                <div class="card-block">
                  <div class="row">
                    <div class="col-md-2">
                      <h5 class="semi-bold no-margin">Code</h5>
                      <h6 class="hint-text">{{ $program->short_code}}</h6>
                    </div>
                    <div class="col-md-4">
                      <h5 class="semi-bold no-margin">Program</h5>
                      <h6 class="hint-text">{{ $program->name }}</h6>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Level</h5>
                      <h6 class="hint-text">{{ $program->level->name }} - {{ $program->level->type}} </h6>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Credits</h5>
                      <h6 class="hint-text">{{ $program->total_credit }}</h6>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Status</h5>
                      <h6 class="hint-text">{{ $program->status }}</h6>
                    </div>
                  </div>
                </div>
                <div class="card-block">
                  <div class="dropdown-divider"></div>
                </div>

                <div class="card-header pt-0">
                  <h4 class="pull-left semi-bold">Modules</h4>
                  <div class="pull-right">
                      {{ Form::open(['route' => ['programs.modules.store', $program]]) }}
                        <div class="input-group form-group  form-group-default-select2">
                          {{ Form::select('module_id', $add_modules->pluck('name', 'id'), null, ['data-init-plugin' => 'select2', 'data-placeholder' => 'Select a module', 'placeholder' => 'Select a module ...']) }}
                          {{ Form::submit('Add', ['class' => 'input-group-addon btn btn-primary px-3']) }}
                        </div>
                      {{ Form::close() }}
                  </div>
                </div>

                <div class="card-block">
                    <div class="table-responsive">
                      <div  class="dataTables_wrapper no-footer">
                        <table class="table table-hover table-condensed dataTable no-footer" role="grid">
                          <thead>
                            <tr role="row">
                              <th style="width: 10%">Code</th>
                              <th style="width: 40%">Name</th>
                              <th style="width: 20%">Credit</th>
                              <th style="width: 20%">Fees</th>
                              <th style="width: 20%">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            @forelse ($program->modules as $module)
                            <tr>
                              <td class="v-align-middle">{{ $module->short_code }}</td>
                              <td class="v-align-middle semi-bold"><a href="{{ route('modules.show', $module) }}">{{ $module->name }}</a></td>
                              <td class="v-align-middle semi-bold">{{ $module->credit }}</td>
                              <td class="v-align-middle semi-bold">MVR {{ $module->fees }}</td>
                              <td class="v-align-middle semi-bold">
                                <form action="{{ route('programs.modules.destroy', [$program, $module]) }}?_method=DELETE" class="delete-onclick inline" method="POST">
                                  @csrf
                                  <button class="btn text-danger btn-link m-0 p-0" type="submit">Remove</button>
                                </form>
                              </td>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                    </div>
        
                    {{-- Default Empty State --}}
                    @component('shared.empty', ['route' => 'modules.index', 'model' => 'modules', 'data' => $program->modules])
                      {{-- Create new Bttn --}}
                    @endcomponent
                  </div>

              </div>
              <!-- END card -->
            </div>


          </div>
        </div>
        <!-- END card -->
      </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection