routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware('auth');

// Admin Routes
Route::namespace('Admin')->middleware('auth')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace

    // Program Routes
    Route::resource('programs', 'ProgramController');
    Route::resource('modules', 'ModuleController');

    // Nested Route for Programs & Modules
    Route::resource('programs.modules', 'ModuleProgramController');

    // Batch
    Route::resource('batches', 'BatchController');
    Route::resource('batches.students', 'BatchStudentController');

    Route::resource('students', 'StudentController');
    Route::resource('vendors', 'VendorController');
    Route::resource('customers', 'CustomerController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('incomes', 'IncomeController');

    Route::get('export', 'StudentController@export')->name('export');
    Route::post('import', 'StudentController@import')->name('import');




});

app/Batch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Batch extends Model
{
    // Mass Assignable Fields
    protected $fillable = [
        'program_id',
        'short_code',
        'status',
        'starts_at',
        'ends_at',
    ];

    // Date Senatize
    public function setStartsAtAttribute($value)
    {
        $this->attributes['starts_at'] =  Carbon::parse($value);
    }

    public function setEndsAtAttribute($value)
    {
        $this->attributes['ends_at'] =  Carbon::parse($value);
    }

    // Relationships
    public function program()
    {
        return $this->belongsTo('App\Program');
    }

    public function students()
    {
        return $this->belongsToMany('App\Student')->withPivot('registration_status');
    }

    public function studentsCount()
    {
        return $this->belongsToMany('App\Student')
            ->selectRaw('count(students.id) as aggregate')
            ->groupBy('pivot_student_id');
    }
    
}

app/Http/Controllers/Admin/BatchController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Batch;
use App\Program;
use App\Student;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\BatchRequest;

class BatchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // Get list of Batchs
        $batches = Batch::when($request->input('q'), function ($query, $q) {
            return $query->where('short_code', 'LIKE', "%${q}%");
            })->orderBy('short_code', 'asc')->with('program')->paginate(14);

        // Get required params
        $programs = Program::where('status', 'active')->get();

        return view('admin.batches.index', compact('batches', 'programs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BatchRequest $request)
    {
        // Store Batches
        Batch::create($request->all());

        // Redirect to index page
        return redirect()->back()->with('success', 'Batch Added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Batch $batch)
    {
        // Eager Load
        $batch->load('students', 'program', 'studentsCount');

        // Send All Modules
        $add_students = Student::whereDoesntHave('batches', function($q) use($batch)
        {
            $q->where('batch_id', $batch->id);
        })->get();
         
        return view('admin.batches.show', compact('batch', 'add_students'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Batch $batch)
    {
        // Get required params
        $programs = Program::where('status', 'active')->get();

        // Return to view
        return view('admin.batches.edit', compact('batch', 'programs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Batch $batch)
    {
        // Get Program
        $batch->update($request->all());

        // Redirect back to Index
        return redirect()->route('batches.index')->with('success', 'Batch Updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Batch $batch)
    {
        // Delete Batch
        $batch->delete();
        return redirect()->route('batches.index')->with('danger', 'Batch Deleted successfully!');
    }
}

resources/views/admin/batches/create.blade.php
<!-- Modal -->
<div class="modal fade slide-up" id="create-batch" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content">
        <div class="modal-header clearfix text-left">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i></button>
          <h5><span class="semi-bold">Add Batch</span></h5>
          <p class="p-b-10">Please make sure all the required information is filled</p>
        </div>
        
        <div class="modal-body">
          {{ Form::open(['route' => 'batches.store', 'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal']) }}
            @include('admin.batches.form') 
          {{ Form::close() }}
        </div>

      </div>
    </div>
    <!-- /.modal-content -->
  </div>
</div>

resources/views/admin/batches/edit.blade.php
@extends('layouts.admin')

@section('title', 'Batches')

@section('content')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
      <div class="col-lg-4 pull-right">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('batches.index') }}">Batches</a></li>
          <li class="breadcrumb-item active">Edit Batch</li>
        </ol>
      </div>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class="no-padding container-fixed-lg bg-white">
      <div class="d-flex justify-content-center ">
          <div class="container card card-default col-6 mt-3">
              <!-- START card -->
                <div class="card-header ">
                  <h5>Edit Batch</h5>
                  <div class="pull-right">
                    <div class="col-xs-12">
                    </div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="card-block">
                  {{ Form::model($batch, ['route' => ['batches.update', $batch],'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal' ]) }}
                  {{ method_field('PATCH') }}
                      @include('admin.batches.form')
                  {{ Form::close() }}
                </div>
              <!-- END card -->
            </div>
      </div>


    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/batches/form.blade.php
<div class="row">
  <div class="col-md-8">
    <div class="form-group form-group-default required {{ $errors->has('short_code') ? 'has-error' :'' }}">
      {{ Form::label('Short Code') }}
      {{ Form::text('short_code', null, ['class' => 'form-control', 'placeholder' => 'Short Code', 'required',]) }}
    </div>
    {!! $errors->first('short_code', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<div class="row clearfix">
  <div class="col-md-12">
      <div class="form-group form-group-default form-group-default-select2 required  {{ $errors->has('program_id') ? 'has-error' :'' }}">
          {{ Form::label('Programs') }}
          {{ Form::select('program_id', $programs->pluck('name', 'id'), null, ['class' => 'full-width', 'data-init-plugin' => 'select2', 'data-placeholder' => 'Select a program', 'placeholder' => 'Select a program']) }}
      </div>
    {!! $errors->first('program_id', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<div class="row clearfix">
    <div class="col-md-6">
        <div class="form-group form-group-default required {{ $errors->has('starts_at') ? 'has-error' :'' }}">
          {{ Form::label('Start Date') }}
          {{ Form::text('starts_at', null, ['class' => 'form-control date', 'placeholder' => 'MM/DD/YYYY', 'required', 'id' => 'datepicker-component', 'autocomplete' => 'off', 'type' => 'date']) }}
        </div>
        {!! $errors->first('starts_at', '<label class="error" for="starts_at">:message</label>') !!}
    </div>
    <div class="col-md-6">
        <div class="form-group form-group-default {{ $errors->has('ends_at') ? 'has-error' :'' }}">
          {{ Form::label('End Date') }}
          {{ Form::text('ends_at', null, ['class' => 'form-control date', 'placeholder' => 'MM/DD/YYYY', 'id' => 'datepicker-component', 'autocomplete' => 'off', 'type' => 'date']) }}
        </div>
        {!! $errors->first('ends_at', '<label class="error" for="ends_at">:message</label>') !!}
    </div>
  </div>

<div class="row clearfix">
  <div class="col-md-6">
      <div class="form-group form-group-default form-group-default-select2 required">
        {{ Form::label('Status') }}
        {{ Form::select('status', config('uyoon.programs.status'), null, ['class' => 'full-width', 'data-init-plugin' => 'select2', 'data-disable-search' => 'true']) }}
      </div>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-8">
  </div>
  <div class="col-md-4 m-t-10 sm-m-t-10">
    {{ Form::submit(isset($batch) ? 'Update Batch' : 'Add Batch', ['class' => 'btn btn-primary btn-block m-t-5']) }}
  </div>
</div>

resources/views/admin/batches/index.blade.php
@extends('layouts.admin')

@section('title', 'Batches')

@section('content')

@include('admin.batches.create')
@include('shared.notifications')

<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="inner" style="transform: translateY(0px); opacity: 1;">
      <!-- START BREADCRUMB -->
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Batchs</li>
      </ol>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" no-padding    container-fixed-lg bg-white">
      <div class="container card card-default">
        <!-- START card -->
        <div class="card card-transparent">
          <div class="card-header ">
            <a class="btn btn-primary btn-cons" href="#" data-target="#create-batch" data-toggle="modal">Add Batch</a>
            <div class="pull-right">
              <div class="col-xs-12">
                <form action="{{ route('batches.index') }}">
                    <div class="input-group transparent center-margin">
                        <input type="text" name="q" class="form-control pull-right" placeholder="Search" value="{{ request()->input('q') }}">
                        <span class="input-group-addon ">
                            <i class="pg-search"></i>
                        </span>
                      </div>
                </form>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="card-block">

            <div class="table-responsive">
              <div  class="dataTables_wrapper no-footer">
                <table class="table table-hover table-condensed dataTable no-footer" role="grid">
                  <thead>
                    <tr role="row">
                      <th style="width: 10%">Code</th>
                      <th style="width: 40%">Program</th>
                      <th style="width: 20%">Status</th>
                      <th style="width: 30%">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($batches as $batch)
                    <tr>
                      <td class="v-align-middle">{{ $batch->short_code }}</td>
                      <td class="v-align-middle semi-bold"><a href="{{ route('batches.show', $batch) }}">{{ $batch->program->name }}</a></td>
                      <td class="v-align-middle semi-bold">{{ $batch->status }}</td>
                      <td class="v-align-middle semi-bold">
                        <a href="{{ route('batches.edit', $batch) }}">Edit</a>
                        <div class="vertical-line"></div>
                        <form action="{{ route('batches.destroy', $batch) }}?_method=DELETE" class="delete-onclick inline" method="POST">
                          @csrf
                          <button class="btn text-danger btn-link m-0 p-0" type="submit">Delete</button>
                          </button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>

            {{-- Default Empty State --}}
            @component('shared.empty', ['route' => 'batches.index', 'model' => 'batches', 'data' => $batches])
              {{-- Create new Bttn --}}
              <a class="btn btn-primary btn-cons" href="#" data-target="#create-batch" data-toggle="modal">Add batch</a>
            @endcomponent

            <div class="mt-3">
                {{ $batches->links() }}
            </div>
          </div>
        </div>
        <!-- END card -->
      </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/batches/show.blade.php
@extends('layouts.admin')

@section('title', 'Batches')

@section('content')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
      <div class="col-lg-6 pull-right">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('batches.index') }}">Batches</a></li>
          <li class="breadcrumb-item active">{{ $batch->short_code }}</li>
        </ol>
      </div>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" no-padding container-fixed-lg bg-white">
      <div class="container card card-default">
        <!-- START card -->
        <div class="card card-transparent">
          <div class="card-header ">
            <h3 class=" no-margin">{{ $batch->short_code }}</h3>
            <div class="pull-right">
              <div class="col-xs-12">
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="card-block">
            <div class="row">
              <!-- START card -->
              <div class="card card-transparent">
                <div class="card-block">
                  <div class="row">
                    <div class="col-md-4">
                      <h5 class="semi-bold no-margin">Program</h5>
                      <h6 class="hint-text">{{ $batch->program->name }}</h6>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Level</h5>
                      <h6 class="hint-text">{{ $batch->program->level->type }} - {{ $batch->program->level->name }} </h6>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Total Students</h5>
                      <h6 class="hint-text">{{ $batch->program->total_credit }}</h6>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Status</h5>
                      <h6 class="hint-text">{{ $batch->status }}</h6>
                    </div>
                  </div>
                </div>
                <div class="card-block">
                  <div class="dropdown-divider"></div>
                </div>

                <div class="card-header pt-0">
                  <h4 class="pull-left semi-bold">Students</h4>
                  <div class="pull-right">
                      {{ Form::open(['route' => ['batches.students.store', $batch]]) }}
                        <div class="input-group form-group  form-group-default-select2">
                          {{ Form::select('student_id', $add_students->pluck('name', 'id'), null, ['data-init-plugin' => 'select2', 'data-placeholder' => 'Select a student', 'placeholder' => 'Select a student']) }}
                          {{ Form::submit('Add', ['class' => 'input-group-addon btn btn-primary px-3']) }}
                        </div>
                      {{ Form::close() }}
                  </div>
                </div>

                <div class="card-block">
                    <div class="table-responsive">
                      <div  class="dataTables_wrapper no-footer">
                        <table class="table table-hover table-condensed dataTable no-footer" role="grid">
                          <thead>
                            <tr role="row">
                              <th style="width: 15%">Student ID</th>
                              <th style="width: 30%">Name</th>
                              <th style="width: 15%">National ID</th>
                              <th style="width: 20%">Mobile Number</th>
                              <th style="width: 15%">Status</th>
                              <th style="width: 30%">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            @forelse ($batch->students as $student)
                            <tr>
                              <td class="v-align-middle">S{{ $student->id }}</td>
                              <td class="v-align-middle semi-bold"><a href="{{ route('students.show', $student) }}">{{ $student->name }}</a></td>
                              <td class="v-align-middle">{{ $student->national_id }}</td>
                              <td class="v-align-middle semi-bold">{{ $student->mobile_number }}</td>
                              <td class="v-align-middle semi-bold">{{ $student->pivot->registration_status }}</td>
                              <td class="v-align-middle semi-bold">
                                <a href="{{ route('students.edit', $student) }}">Edit</a>
                                <div class="vertical-line"></div>
                                <form action="{{ route('batches.students.destroy', [$batch, $student]) }}?_method=DELETE" class="delete-onclick inline" method="POST">
                                  @csrf
                                  <button class="btn text-danger btn-link m-0 p-0" type="submit">Remove</button>
                                  </button>
                                </form>
                              </td>
                            </tr>
                            @endforeach
                          </tbody>
                        </table>
                      </div>
                    </div>
        
                    {{-- Default Empty State --}}
                    @component('shared.empty', ['route' => 'students.index', 'model' => 'students', 'data' => $batch->students])
                      {{-- Create new Bttn --}}
                    @endcomponent
                  </div>

              </div>
              <!-- END card -->
            </div>


          </div>
        </div>
        <!-- END card -->
      </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection