routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware('auth');

// Admin Routes
Route::namespace('Admin')->middleware('auth')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace

    // Program Routes
    Route::resource('programs', 'ProgramController');
    Route::resource('modules', 'ModuleController');

    // Nested Route for Programs & Modules
    Route::resource('programs.modules', 'ModuleProgramController');

    // Batch
    Route::resource('batches', 'BatchController');
    Route::resource('batches.students', 'BatchStudentController');

    Route::resource('students', 'StudentController');
    Route::resource('vendors', 'VendorController');
    Route::resource('customers', 'CustomerController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('incomes', 'IncomeController');

    Route::get('export', 'StudentController@export')->name('export');
    Route::post('import', 'StudentController@import')->name('import');




});

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
    // Mass Assignable Fields
    protected $fillable = [
        'name',
        'short_code',
        'credit',
        'fees',
        'repeat_fees',
        'learning_hours',
        'contact_hours',
    ];

    /* Relationships */

    // Programs that has Modules
    public function programs()
    {
        return $this->belongsToMany('App\Program');
    }
}

app/Http/Controllers/Admin/ModuleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Module;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ModuleRequest;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        // Get Modules
        $modules = Module::when($request->input('q'), function ($query, $q) {
            return $query->where('short_code', 'LIKE', "%${q}%")->orWhere('name', 'LIKE', "%${q}%");
            })->orderBy('name', 'asc')->paginate(14);

        // Return to view
        return view('admin.modules.index', compact('modules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ModuleRequest $request, Module $module)
    {
        // Create Module
        $module->create($request->all());

        // Redict to Back
        return redirect()->back()->with('success', 'Module Created successfully!');;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Module $module)
    {
        return view('admin.modules.edit', compact('module'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Module $module)
    {
        // Get Program
        $module->update($request->all());
        
        // Redirect back to Index
        return redirect()->route('modules.index')->with('success', 'Module Updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Module $module)
    {
        $module->delete();
        return redirect()->route('modules.index')->with('danger', 'Module Deleted successfully!');;
    }
}

resources/views/admin/modules/create.blade.php
<!-- Modal -->
<div class="modal fade slide-up" id="create-module" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog ">
    <div class="modal-content-wrapper">
      <div class="modal-content">
        <div class="modal-header clearfix text-left">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i></button>
          <h5><span class="semi-bold">Add Module</span></h5>
          <p class="p-b-10">Please make sure all the required information is filled</p>
        </div>
        
        <div class="modal-body">
          {{ Form::open(['route' => 'modules.store', 'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal']) }}
            @include('admin.modules.form') 
          {{ Form::close() }}
        </div>

      </div>
    </div>
    <!-- /.modal-content -->
  </div>
</div>

resources/views/admin/modules/edit.blade.php
@extends('layouts.admin')

@section('title', 'Program')
@section('content')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
      <div class="col-lg-4 pull-right">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('modules.index') }}">Modules</a></li>
          <li class="breadcrumb-item active">Edit Module</li>
        </ol>
      </div>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class="no-padding container-fixed-lg bg-white">
      <div class="d-flex justify-content-center ">
          <div class="container card card-default col-6 mt-3">
              <!-- START card -->
                <div class="card-header ">
                  <h5>Edit Module</h5>
                  <div class="pull-right">
                    <div class="col-xs-12">
                    </div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="card-block">
                  {{ Form::model($module, ['route' => ['modules.update', $module],'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal' ]) }}
                  {{ method_field('PATCH') }}
                      @include('admin.modules.form')
                  {{ Form::close() }}
                </div>
              <!-- END card -->
            </div>
      </div>


    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/modules/form.blade.php
<p class="m-t-10">Module Information</p>

<div class="row">
  <div class="col-md-8">
    <div class="form-group form-group-default required {{ $errors->has('short_code') ? 'has-error' :'' }}">
      {{ Form::label('Short Code') }}
      {{ Form::text('short_code', null, ['class' => 'form-control', 'placeholder' => 'Short Code', 'required',]) }}
    </div>
    {!! $errors->first('short_code', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<div class="row clearfix">
  <div class="col-md-12">
    <div class="form-group form-group-default required {{ $errors->has('name') ? 'has-error' :'' }}">
      {{ Form::label('Module name') }}
      {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Module Name', 'required']) }}
    </div>
    {!! $errors->first('name', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<p class="m-t-10">Module Specification</p>
<div class="row clearfix">
  <div class="col-md-8">
    <div class="form-group form-group-default required {{ $errors->has('credit') ? 'has-error' :'' }}">
      {{ Form::label('Credit') }}
      {{ Form::number('credit', null, ['class' => 'form-control', 'placeholder' => 'Credit', 'required']) }}
    </div>
    {!! $errors->first('credit', '<label class="error" for="credit">:message</label>') !!}
  </div>
</div>

<div class="row clearfix">
  <div class="col-md-6">
    <div class="form-group form-group-default input-group required {{ $errors->has('fees') ? 'has-error' :'' }}">
        <div class="input-group-addon">
            MVR
        </div>
        <div class="form-input-group">
            {{ Form::label('Fees') }}
            {{ Form::number('fees', null, ['class' => 'form-control', 'placeholder' => 'Fees', 'required']) }}
        </div>

      </div>
    {!! $errors->first('fees', '<label class="error" for="name">:message</label>') !!}
  </div>

  <div class="col-md-6">
      <div class="form-group form-group-default input-group required {{ $errors->has('repeat_fees') ? 'has-error' :'' }}">
          <div class="input-group-addon">
              MVR
          </div>
          <div class="form-input-group">
              {{ Form::label('Repeat Fees') }}
              {{ Form::number('repeat_fees', null, ['class' => 'form-control', 'placeholder' => 'Repeat Fees', 'required']) }}
          </div>
        </div>
    {!! $errors->first('repeat_fees', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<div class="row clearfix">
  <div class="col-md-6">
    <div class="form-group form-group-default input-group {{ $errors->has('learning_hours') ? 'has-error' :'' }}">
      <div class="form-input-group">
          {{ Form::label('Learning Hours') }}
          {{ Form::number('learning_hours', null, ['class' => 'form-control', 'placeholder' => 'Learning Hours']) }}
      </div>
      <div class="input-group-addon">
        Hours
      </div>
    </div>
    {!! $errors->first('learning_hours', '<label class="error" for="name">:message</label>') !!}
  </div>

  <div class="col-md-6">
    <div class="form-group form-group-default input-group {{ $errors->has('contact_hours') ? 'has-error' :'' }}">
        <div class="form-input-group">
            {{ Form::label('Contact Hours') }}
            {{ Form::number('contact_hours', null, ['class' => 'form-control', 'placeholder' => 'Contact Hours']) }}
        </div>
        <div class="input-group-addon">
          Hours
        </div>
      </div>
     {!! $errors->first('contact_hours', '<label class="error" for="name">:message</label>') !!}
  </div>
</div>

<hr>

<div class="row">
  <div class="col-md-8">

  </div>
  <div class="col-md-4 m-t-10 sm-m-t-10">
    {{ Form::submit(isset($module) ? 'Update Module' : 'Add Module', ['class' => 'btn btn-primary btn-block m-t-5']) }}
  </div>
</div>

resources/views/admin/modules/index.blade.php
@extends('layouts.admin')

@section('title', 'Modules')

@section('content')

@include('admin.modules.create')
@include('shared.notifications')

<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="inner" style="transform: translateY(0px); opacity: 1;">
      <!-- START BREADCRUMB -->
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Modules</li>
      </ol>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" no-padding    container-fixed-lg bg-white">
      <div class="container card card-default">
        <!-- START card -->
        <div class="card card-transparent">
          <div class="card-header ">
            <a class="btn btn-primary btn-cons" href="#" data-target="#create-module" data-toggle="modal">Add Module</a>
            <div class="pull-right">
              <div class="col-xs-12">
                <form action="{{ route('modules.index') }}">
                    <div class="input-group transparent center-margin">
                        <input type="text" name="q" class="form-control pull-right" placeholder="Search" value="{{ request()->input('q') }}">
                        <span class="input-group-addon ">
                            <i class="pg-search"></i>
                        </span>
                    </div>
                </form>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="card-block">

            <div class="table-responsive">
              <div  class="dataTables_wrapper no-footer">
                <table class="table table-hover table-condensed dataTable no-footer" role="grid">
                  <thead>
                    <tr role="row">
                      <th style="width: 10%">Code</th>
                      <th style="width: 40%">Name</th>
                      <th style="width: 20%">Credit</th>
                      <th style="width: 20%">Fees</th>
                      <th style="width: 20%">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($modules as $module)
                    <tr>
                      <td class="v-align-middle">{{ $module->short_code }}</td>
                      <td class="v-align-middle semi-bold"><a href="{{ route('modules.show', $module) }}">{{ $module->name }}</a></td>
                      <td class="v-align-middle semi-bold">{{ $module->credit }}</td>
                      <td class="v-align-middle semi-bold">MVR {{ $module->fees }}</td>
                      <td class="v-align-middle semi-bold">
                        <a href="{{ route('modules.edit', $module) }}">Edit</a>
                        <div class="vertical-line"></div>
                        <form action="{{ route('modules.destroy', $module) }}?_method=DELETE" class="delete-onclick inline" method="POST">
                          @csrf
                          <button class="btn text-danger btn-link m-0 p-0" type="submit">Delete</button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>

            {{-- Default Empty State --}}
            @component('shared.empty', ['route' => 'modules.index', 'model' => 'modules', 'data' => $modules])
              {{-- Create new Bttn --}}
              <a class="btn btn-primary btn-cons" href="#" data-target="#create-module" data-toggle="modal">Add Module</a>
            @endcomponent

            <div class="mt-3">
                {{ $modules->links() }}
            </div>
          </div>
        </div>
        <!-- END card -->
      </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/modules/show.blade.php
@extends('layouts.admin')

@section('content')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
      <div class="col-lg-6 pull-right">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('programs.index') }}">Programs</a></li>
          <li class="breadcrumb-item active">{{ $program->name }}</li>
        </ol>
      </div>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" no-padding container-fixed-lg bg-white">
      <div class="container card card-default">
        <!-- START card -->
        <div class="card card-transparent">
          <div class="card-header ">
            <div class="card-title">Programs</div>
            <h3 class="text-primary no-margin">{{ $program->name }}</h3>
            <div class="pull-right">
              <div class="col-xs-12">
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="card-block">

            <div class="row">
              <!-- START card -->
              <div class="card card-transparent">
                <div class="card-block">
                  <div class="row">
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Code</h5>
                      <p class="hint-text">{{ $program->short_code}}</p>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Program</h5>
                      <p class="hint-text">{{ $program->name }}</p>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Level</h5>
                      <p class="hint-text">{{ $program->level->name }} - {{ $program->level->type}} </p>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Total Credits</h5>
                      <p class="hint-text">{{ $program->total_credit }}</p>
                    </div>
                    <div class="col-md">
                      <h5 class="semi-bold no-margin">Status</h5>
                      <p class="hint-text">{{ $program->status }}</p>
                    </div>
                  </div>
                </div>

                <div class="card-block">
                  <div class="table-responsive">
                    <div id="condensedTable_wrapper" class="dataTables_wrapper no-footer">
                      <table class="table table-hover table-condensed dataTable no-footer" id="condensedTable" role="grid">
                        <thead>
                          <tr role="row">
                            <th style="width:1%" class="text-center sorting_disabled" rowspan="1" colspan="1"
                              aria-label="">
                              <button class="btn btn-link"><i class="pg-trash"></i>
                              </button>
                            </th>
                            <th style="width: 40%">Name</th>
                            <th style="width: 20%">Code</th>
                            <th style="width: 10%">Credit</th>
                            <th style="width: 20%">Status</th>
                            <th style="width: 30%">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {{-- @foreach ($programs as $program)
                          <tr>
                            <td class="v-align-middle semi-bold"><input type="checkbox" value="3" id="checkbox1"><label
                                for="checkbox1" class="no-padding no-margin"></label></td>
                            <td class="v-align-middle semi-bold">{{ $program->name }}</td>
                            <td class="v-align-middle">{{ $program->short_code }}</td>
                            <td class="v-align-middle semi-bold">{{ $program->total_credit }}</td>
                            <td class="v-align-middle semi-bold">{{ $program->status }}</td>
                            <td class="v-align-middle semi-bold">
                              <a class="btn btn-defaultr btn-xs" href="{{ route('programs.show', ['id' => $program->id ]) }}"><i
                                  class="fa fa-eye"></i>
                                <span class="bold">View Program</span>
                              </a>
                              <a class="btn btn-default btn-xs" href="{{ route('programs.edit', ['id' => $program->id ]) }}"><i
                                  class="fa  fa-edit"></i>
                                <span class="bold">Edit</span>
                              </a>
                              <form action="?_method=DELETE" class="delete-onclick inline" method="POST">
                                @csrf
                                <button class="btn btn-danger btn-xs" type="submit"><i class="fa fa-trash-o"></i>
                                  <span class="bold">Delete</span>
                                </button>
                              </form>
                            </td>
                          </tr>
                          @endforeach --}}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <!-- END card -->
            </div>


          </div>
        </div>
        <!-- END card -->
      </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection