routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->middleware('auth');

// Admin Routes
Route::namespace('Admin')->middleware('auth')->group(function () {
    // Controllers Within The "App\Http\Controllers\Admin" Namespace

    // Program Routes
    Route::resource('programs', 'ProgramController');
    Route::resource('modules', 'ModuleController');

    // Nested Route for Programs & Modules
    Route::resource('programs.modules', 'ModuleProgramController');

    // Batch
    Route::resource('batches', 'BatchController');
    Route::resource('batches.students', 'BatchStudentController');

    Route::resource('students', 'StudentController');
    Route::resource('vendors', 'VendorController');
    Route::resource('customers', 'CustomerController');
    Route::resource('expenses', 'ExpenseController');
    Route::resource('incomes', 'IncomeController');

    Route::get('export', 'StudentController@export')->name('export');
    Route::post('import', 'StudentController@import')->name('import');




});

resources/views/admin/expenses/create.blade.php
<!-- Modal -->
<div class="modal fade slide-up" id="create-expense" tabindex="-1" role="dialog" aria-hidden="false">
  <div class="modal-dialog modal-lg" >
    <div class="modal-content-wrapper" >
      <div class="modal-content" >
        <div class="modal-header clearfix text-left">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i></button>
          <h5><span class="semi-bold">Add Expense</span></h5>
          <p class="p-b-10">Please make sure all the required information is filled</p>
        </div>
        
        <div class="modal-body">
          {{ Form::open(['route' => 'expenses.store', 'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal']) }}
            @include('admin.expenses.form') 
          {{ Form::close() }}
        </div>

      </div>
    </div>
    <!-- /.modal-content -->
  </div>
</div>

resources/views/admin/expenses/edit.blade.php
@extends('layouts.admin')

@section('title', 'Expense')
@section('content')
<!-- START PAGE CONTENT -->
<div class="content ">
  <!-- START JUMBOTRON -->
  <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
      <div class="col-lg-4 pull-right">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="{{ route('expenses.index') }}">Expense</a></li>
          <li class="breadcrumb-item active">Edit Expense</li>
        </ol>
      </div>
      <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class="no-padding container-fixed-lg bg-white">
      <div class="d-flex justify-content-center ">
          <div class="container card card-default col-10 mt-3">
              <!-- START card -->
                <div class="card-header ">
                  <h5>Edit Expense</h5>
                  <div class="pull-right">
                    <div class="col-xs-12">
                    </div>
                  </div>
                  <div class="clearfix"></div>
                </div>
                <div class="card-block">
                  {{ Form::model($expense, ['route' => ['expenses.update', $expense],'novalidate' => 'novalidate', 'role' => 'form', 'id' => 'form-personal' ]) }}
                  {{ method_field('PATCH') }}
                      @include('admin.expenses.form')
                  {{ Form::close() }}
                </div>
              <!-- END card -->
            </div>
      </div>


    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
  </div>
  <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/expenses/form.blade.php
<div class="row clearfix">
        <div class="col-md-6" style="padding-left: 7px";>
                <div class="form-group form-group-default form-group-default-select2 required">
                    <label class="">Vendor</label>
                    <select class="full-width" data-placeholder="Select Vendor" data-init-plugin="select2" name="vendor_id">
                        @foreach ($vendors as $vendor)
                        <option value="{{ $vendor->id }}"
                            {{ isset($expense) ? ($vendor->id == $expense->vendor_id ? 'selected' : '') : '' }}>{{
                            $vendor->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        <div class="col-md-6">
            <div class="form-group form-group-default required {{ $errors->has('title') ? 'has-error' :'' }}">
            {{ Form::label('Title') }}
            {{ Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title', 'required',]) }}
            </div>
            {!! $errors->first('title', '<label class="error" for="name">:message</label>') !!}
        </div>

            <div class="col-md-12">
              <div class="form-group form-group-default required {{ $errors->has('description') ? 'has-error' :'' }}">
                {{ Form::label('Description') }}
                {{ Form::text('description', null, ['class' => 'form-control', 'placeholder' => 'Description', 'required',]) }}
              </div>
              {!! $errors->first('description', '<label class="error" for="name">:message</label>') !!}
            </div>
            <div class="col-md-6">
              <div class="form-group form-group-default form-group-default-select2 required">
                {{ Form::label('Type') }}
                {{ Form::select('type', ['Cash' => 'Cash', 'Cheque' => 'Cheque'], null, ['class' => 'full-width', 'data-init-plugin' => 'select2', 'data-disable-search' => 'true']) }}
              </div>
          </div>

            {{-- <div class="col-md-6">
                <div class="form-group form-group-default form-group-default-select2 required">
                  <label class="">Type</label>
                  <select class="full-width" data-placeholder="Select Type" data-init-plugin="select2" name="type"> 
                        <option value=""></option>
                        <option value="Cash">Cash</option>
                        <option value="Cheque">Cheque</option>
                  </select>
                </div> 
            </div> --}}

                {{-- <div class="col-md-6">
                  <div class="form-group form-group-default required {{ $errors->has('type') ? 'has-error' :'' }}">
                    {{ Form::label('Type') }}
                    {{ Form::text('type', null, ['class' => 'form-control', 'placeholder' => 'Type', 'required',]) }}
                  </div>
                  {!! $errors->first('type', '<label class="error" for="name">:message</label>') !!}
                </div> --}}
                <div class="col-md-6 clearfix">
                  <div class="form-group form-group-default  {{ $errors->has('cheque_number') ? 'has-error' :'' }}">
                    {{ Form::label('Cheque Number') }}
                    {{ Form::text('cheque_number', null, ['class' => 'form-control', 'placeholder' => 'Cheque Number', ]) }}
                  </div>
                  {!! $errors->first('cheque_number', '<label class="error" for="name">:message</label>') !!}
                </div>

                <div class="col-md-6">
                  <div class="form-group form-group-default  {{ $errors->has('receipt_number') ? 'has-error' :'' }}">
                    {{ Form::label('Reciept Number') }}
                    {{ Form::text('receipt_number', null, ['class' => 'form-control', 'placeholder' => 'Reciept Number', ]) }}
                  </div>
                  {!! $errors->first('receipt_number', '<label class="error" for="name">:message</label>') !!}
                </div>
                <div class="col-md-6 clearfix">
                  <div class="form-group form-group-default required {{ $errors->has('date') ? 'has-error' :'' }}">
                    {{ Form::label('Date') }}
                    {{ Form::text('date', null, ['class' => 'form-control', 'placeholder' => 'Date', 'required', 'id' => 'datepicker-component2', 'data-date-format' => 'yyyy-mm-dd',]) }}
                  </div>
                  {!! $errors->first('date', '<label class="error" for="name">:message</label>') !!}
                </div>                
                {{-- <div class="col-md-6 clearfix">
                  <div class="form-group form-group-default required {{ $errors->has('pv_number') ? 'has-error' :'' }}">
                    {{ Form::label('Purchase Voucher') }}
                    {{ Form::text('pv_number', null, ['class' => 'form-control', 'placeholder' => 'Purchase Voucher', 'required',])}}                    
                  </div>
                  {!! $errors->first('pv_number', '<label class="error" for="name">:message</label>') !!}
                </div> --}}
                <div class="col-md-6">
                  <div class="form-group form-group-default required {{ $errors->has('amount') ? 'has-error' :'' }}">
                    {{ Form::label('Amount') }}
                    {{ Form::number('amount', null, ['class' => 'form-control', 'placeholder' => 'Amount', 'required',]) }}
                    {{ Form::hidden('paid_by',Auth()->user()->name, ['class' => 'form-control',]) }}
                  </div>
                  {!! $errors->first('amount', '<label class="error" for="name">:message</label>') !!}
                </div>




{{--  <div class="row">
    <div class="form-group form-group-default input-group col-md-4">
        <div class="form-input-group">
            <label class="fade">Date</label>
            <input name="date" type="text" class="form-control" value="{{ old('date') ?? (isset($expense) ? $expense->date : null) }}" placeholder="Pick paid date" id="datepicker-component2">
</div>
</div></div>  --}}

</div>
<hr>
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4 m-t-10 sm-m-t-10">
      {{ Form::submit(isset($expense) ? 'Update Expense' : 'Add Expense', ['class' => 'btn btn-primary btn-block m-t-5']) }}
    </div>
  </div>

resources/views/admin/expenses/index.blade.php
@extends('layouts.admin')

@section('title', 'Expenses')

@section('content')

@include('admin.expenses.create')
@include('shared.notifications')

<!-- START PAGE CONTENT -->
<div class="content ">
    <!-- START JUMBOTRON -->
    <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
        <div class="inner" style="transform: translateY(0px); opacity: 1;">
            <!-- START BREADCRUMB -->
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                <li class="breadcrumb-item active">Expenses</li>
            </ol>
            <!-- END BREADCRUMB -->
        </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" no-padding    container-fixed-lg bg-white">
        <div class="container card card-default">
            <!-- START card -->
            <div class="card card-transparent">
                <div class="card-header ">
                    <a class="btn btn-primary btn-cons" href="#" data-target="#create-expense" data-toggle="modal"></i>
                        Add Expense</a>
                    <div class="pull-right">
                        <div class="col-xs-12">
                            <form action="{{ route('expenses.index') }}">
                                    <div class="input-group transparent center-margin">
                                        <input type="text" name="q" class="form-control pull-right" placeholder="Search" value="{{ request()->input('q') }}">
                                        <span class="input-group-addon ">
                                            <i class="pg-search"></i>
                                        </span>
                                    </div>
                            </form>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="card-block">                  

                    <div class="table-responsive">
                        <div class="dataTables_wrapper no-footer">
                            <table class="table table-hover table-condensed dataTable no-footer" role="grid">
                                <thead>
                                    <tr role="row">
                                        <th style="width: 15%">Vendor Name</th>
                                        <th style="width: 20%">Title</th>
                                        <th style="width: 15%">Purchase Voucher</th>
                                        <th style="width: 10%">Type</th>
                                        <th style="width: 10%">Amount</th>
                                        <th style="width: 20%">Action</th>
                                    </tr>
                                </thead> 
                                <tbody>
                                    @foreach ($expenses as $expense)
                                    <tr>                                        
                                        <td class="v-align-middle semi-bold">{{ $expense->vendor->name }}</td>
                                        <td class="sorting v-align-middle semi-bold"><a href="{{ route('expenses.show', $expense) }}">{{
                                            $expense->title }}</a></td>
                                        <td class="v-align-middle semi-bold">{{ $expense->pv_number }}</td>
                                        <td class="v-align-middle semi-bold">{{ $expense->type }}</td>
                                        <td class="v-align-middle semi-bold">{{ $expense->amount }}</td>
                                        <td class="v-align-middle semi-bold">
                                            <a href="{{ route('expenses.edit', $expense) }}">Edit</a>
                                            <div class="vertical-line"></div>
                                            <form action="{{ route('expenses.destroy', ['id' => $expense->id ]) }}?_method=DELETE"
                                                class="delete-onclick inline" method="POST">
                                                @csrf
                                                <button class="btn text-danger btn-link m-0 p-0" type="submit">Delete</button>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>

                    {{-- Default Empty State --}}
                    @component('shared.empty', ['route' => 'expenses.index', 'model' => 'expenses', 'data' =>
                    $expenses])
                    {{-- Create new Bttn --}}
                    <a class="btn btn-primary btn-cons" href="#" data-target="#create-expense" data-toggle="modal">Add
                        Expense</a>
                    @endcomponent

                    <div class="mt-3">
                        {{ $expenses->links() }}
                    </div>
                </div>
            </div>
            <!-- END card -->           
        </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <!-- START CONTAINER FLUID -->
    <!-- END CONTAINER FLUID -->
    </div>
    <!-- END PAGE CONTENT -->
</div>
@endsection

resources/views/admin/expenses/show.blade.php
@extends('layouts.admin')


@section('title', 'Expenses')


@section('content')
<!-- START JUMBOTRON -->
<div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
    <div class="row">
        <div class="col-lg-4 pull-right">
            <!-- START BREADCRUMB -->
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ route('expenses.index') }}">Expense</a></li>
                <li class="breadcrumb-item active">Expense Details</li>
            </ol>
        </div>
        <!-- END BREADCRUMB -->
    </div>

    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
<div>
   <div class=" no-padding container-fixed-lg bg-white">
        <div class="container card card-default">
            <!-- START card -->
            <div class="card card-transparent">
                    <div class="card-header ">         
                    <div class="row">
                            <div class="col-md-8">
                                <h4>Expense Details</h4>
                            </div>
                            <div class="col-md-4">
                                <div class="pull-right">
                                    <h5  >Purchase Voucher: {{ $expense->pv_number}}</h5>                        
                                  </div>
                            </div>
                          </div>
                </div>
                <div class="card-block">
                    <form id="form-personal" role="form" novalidate="novalidate" action="" method="POST">
                        <!-- START card -->
                        <div class="card card-transparent">
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h5 class="semi-bold no-margin">Title</h5>
                                        <h6 class="">{{ $expense->title}}</h5>
                                    </div>
                                    <div class="col-md-2">
                                        <h5 class="semi-bold no-margin">Type</h5>
                                        <h6 class="">{{ $expense->type }}</h6>
                                    </div>
                                    <div class="col-md-4">
                                        <h5 class="semi-bold no-margin">Description</h5>
                                        <h6 class="">{{ $expense->description}}</h5>
                                    </div>
                                    <div class="col-md-3">
                                        <h5 class="semi-bold no-margin">Date</h5>
                                        <h6 class="">{{ $expense->date }}</h6>
                                    </div>                                    
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-md-2">
                                        <h5 class="semi-bold no-margin">Cheque Number</h5>
                                        <h6 class="">{{ $expense->cheque_number}}</h5>
                                    </div>

                                    <div class="col-md-2">
                                        <h5 class="semi-bold no-margin">Paid by</h5>
                                        <h6 class="">{{ $expense->paid_by}}</h5>
                                    </div>
                                    <div class="col-md-2">
                                        <h5 class="semi-bold no-margin">Receipt Number</h5>
                                        <h6 class="">{{ $expense->receipt_number }}</h6>
                                    </div>
                                    <div class="col-md-3">
                                        <h5 class="semi-bold no-margin">Created at</h5>
                                        <h6 class="">{{ $expense->created_at }}</h6>
                                    </div>
                                    <div class="col-md-3">
                                        <h5 class="semi-bold no-margin">Last Updated at</h5>
                                        <h6 class="">{{ $expense->updated_at }}</h6>
                                    </div>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
            <!-- END card -->
        </div>
    </div>
    
</div>
<div>
   <div class=" no-padding container-fixed-lg bg-white">
        <div class="container card card-default">
            <!-- START card -->
            <div class="card card-transparent">
                <div class="card-header ">
                  <div class="row">
                    <div class="col-md-8">
                        <h4>Vendor Details</h4>
                    </div>
                    <div class="col-md-4">
                        <div class="pull-right">
                            <h5 >TIN: {{ $expense->vendor->tin_number}}</h5>                        
                          </div>
                    </div>
                  </div>
                    
                    
                    <div class="clearfix"></div>
                </div>
                <div class="card-block">
                    <form id="form-personal" role="form" novalidate="novalidate" action="" method="POST">
                        <!-- START card -->
                        <div class="card card-transparent">
                            <div class="card-block">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h5 class="semi-bold no-margin">Name</h5>
                                        <h6 class="">{{ $expense->vendor->name}}</h5>
                                    </div>
                                    <div class="col-md-4">
                                        <h5 class="semi-bold no-margin">Address</h5>
                                        <h6 class="">{{ $expense->vendor->address }}</h6>
                                    </div>
                                    <div class="col-md-3">
                                        <h5 class="semi-bold no-margin">Email</h5>
                                        <h6 class="">{{ $expense->vendor->email}}</h5>
                                    </div>
                                    <div class="col-md-2">
                                        <h5 class="semi-bold no-margin">Mobile Number</h5>
                                        <h6 class="">{{ $expense->vendor->mobile_number }}</h6>
                                    </div>                                  
                                </div>                              
                            </div>
                    </form>
                </div>
            </div>
            <!-- END card -->
        </div>
    </div>
    
</div>


<!-- END PAGE CONTENT -->
</div>
@endsection